### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by bhrutledge** [roperi/myband#5]
For why and how, see:

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

I just added the MIT License to https://github.com/bhrutledge/jahhills.com/.

**Comment by roperi** [comment]
Never thought of this. Thanks for the heads up. 

Done. See ec19556
