### ISSUE TITLE
Update repository details

### ISSUE THREAD

**Issue by bhrutledge** [roperi/myband#7]
i.e., the "About" sidebar, via the gear icon.

<img width="873" alt="Screen Shot 2021-02-15 at 6 12 13 PM" src="https://user-images.githubusercontent.com/1326704/108001033-63448580-6fb9-11eb-899d-870eac1aeaec.png">

**Comment by roperi** [comment]
Thanks for pointing it out! Done!

**Comment by bhrutledge** [comment]
Awesome. FWIW, I'd remove the "Based on https://github.com/bhrutledge/jahhills.com in its entirety." from the description, since it's in your README, and it makes the HTML page title really long:

```
<title>roperi/myband: This is a band&#39;s website using Django. Based on https://github.com/bhrutledge/jahhills.com in its entirety.</title>
```

Also, I like to disable "Releases", "Packages", and "Environments", to keep things tidy.

And finally, I'd remove `www.myband.com`, since that's a real website: https://www.myband.com/. I was thinking you could put https://coctelduo.com/ there.

**Comment by roperi** [comment]
Done!

**Comment by roperi** [comment]
I forgot to mention I put myband.com because I thought of  using 'myband.com' as a placeholder wherever it is hardcoded in the code so other people can easily just change it to their respective band name. But I'm not sure if that's a good idea anymore.

**Comment by bhrutledge** [comment]
Yeah, I've previously attempted to make a "generic Django band website", but that required a lot more work than making it specific to my band. I like your approach so far of taking what I've written, and customizing it for your needs. If you ever get into the business of making band websites, then maybe you could make it generic.
